const express = require("express");
const { asyncHandler } = require("../utils/async-handler");
const { requireAuth } = require("../middleware/auth");
const { listReports, getReportById } = require("../services/report-service");

const router = express.Router();

router.get(
  "/",
  requireAuth,
  asyncHandler(async (req, res) => {
    const reports = await listReports(req.auth.sub);
    res.json({ reports });
  })
);

router.get(
  "/:reportId/download",
  requireAuth,
  asyncHandler(async (req, res) => {
    const report = await getReportById(req.auth.sub, req.params.reportId);
    const payload = [
      "SMARTMED MEDICAL REPORT",
      `Title: ${report.title}`,
      `Type: ${report.type}`,
      `Status: ${report.status}`,
      `Doctor: ${report.doctorName}`,
      `Date: ${report.date}`,
      "",
      "This exported document is generated by SmartMed.",
    ].join("\n");

    res.setHeader(
      "Content-Disposition",
      `attachment; filename="${report.title.replace(/\s+/g, "-").toLowerCase()}.txt"`
    );
    res.type("text/plain").send(payload);
  })
);

module.exports = router;
