const PDFDocument = require("pdfkit");

const BRAND_COLOR = "#0f766e";
const MUTED_COLOR = "#5f7383";
const TEXT_COLOR = "#10202b";
const BORDER_COLOR = "#d7e2e0";

const addLabelValue = (doc, label, value) => {
  if (!value) {
    return;
  }

  doc
    .fontSize(9)
    .fillColor(MUTED_COLOR)
    .font("Helvetica-Bold")
    .text(label.toUpperCase(), { continued: false });

  doc
    .fontSize(11)
    .fillColor(TEXT_COLOR)
    .font("Helvetica")
    .text(value, { paragraphGap: 12 });
};

// Streams a styled PDF for a single medical report directly onto the given
// HTTP response. Keeps SmartMed's brand color and a clean, presentation-safe
// layout rather than a bare text dump.
const streamReportPdf = (res, report) => {
  const doc = new PDFDocument({ size: "A4", margin: 50 });
  doc.pipe(res);

  // Header band
  doc.rect(0, 0, doc.page.width, 90).fill(BRAND_COLOR);
  doc
    .fillColor("#ffffff")
    .font("Helvetica-Bold")
    .fontSize(20)
    .text("SmartMed", 50, 30);
  doc
    .fillColor("#e6fffa")
    .font("Helvetica")
    .fontSize(10)
    .text("AI-assisted care workspace — Medical Report", 50, 56);

  doc.moveDown(3);
  doc.y = 120;

  doc
    .fillColor(TEXT_COLOR)
    .font("Helvetica-Bold")
    .fontSize(18)
    .text(report.title, 50, 120);

  doc
    .fillColor(MUTED_COLOR)
    .font("Helvetica")
    .fontSize(10)
    .text(`${report.type} • Status: ${report.status}`, { paragraphGap: 16 });

  doc
    .moveTo(50, doc.y)
    .lineTo(doc.page.width - 50, doc.y)
    .strokeColor(BORDER_COLOR)
    .stroke();
  doc.moveDown(1);

  addLabelValue(doc, "Referred by", report.doctorName);
  addLabelValue(doc, "Date", report.date);
  if (report.specialist) {
    addLabelValue(doc, "Recommended specialist", report.specialist);
  }
  if (report.severity) {
    addLabelValue(doc, "Severity", report.severity);
  }
  if (report.matchedSymptoms && report.matchedSymptoms.length > 0) {
    addLabelValue(doc, "Matched symptoms", report.matchedSymptoms.join(", "));
  }
  if (report.summary) {
    addLabelValue(doc, "Summary", report.summary);
  }
  if (report.medicine) {
    addLabelValue(doc, "Suggested medicine / OTC", report.medicine);
  }
  if (report.advice) {
    addLabelValue(doc, "Advice", report.advice);
  }

  doc.moveDown(1);
  doc
    .moveTo(50, doc.y)
    .lineTo(doc.page.width - 50, doc.y)
    .strokeColor(BORDER_COLOR)
    .stroke();
  doc.moveDown(0.8);

  doc
    .fontSize(8)
    .fillColor(MUTED_COLOR)
    .font("Helvetica-Oblique")
    .text(
      "This report is generated by SmartMed for educational and informational support only. " +
        "It is not a substitute for professional medical diagnosis or treatment.",
      { width: doc.page.width - 100 }
    );

  doc.end();
};

module.exports = { streamReportPdf };
