const symptomCatalog = [
  {
    key: "fever",
    label: "Fever",
    aliases: ["fever", "temperature", "mild fever", "feverish", "body temperature high"],
    bodySystems: ["general"],
    severityHint: "medium",
  },
  {
    key: "high_fever",
    label: "High Fever",
    aliases: ["high fever", "very high fever", "temperature above 102", "persistent high fever"],
    bodySystems: ["general"],
    severityHint: "high",
  },
  {
    key: "chills",
    label: "Chills",
    aliases: ["chills", "shivering", "feeling cold with fever"],
    bodySystems: ["general"],
    severityHint: "medium",
  },
  {
    key: "cough",
    label: "Cough",
    aliases: ["cough", "coughing"],
    bodySystems: ["respiratory"],
    severityHint: "medium",
  },
  {
    key: "dry_cough",
    label: "Dry Cough",
    aliases: ["dry cough", "non productive cough", "tickly cough"],
    bodySystems: ["respiratory"],
    severityHint: "medium",
  },
  {
    key: "productive_cough",
    label: "Productive Cough",
    aliases: ["productive cough", "wet cough", "cough with mucus", "phlegm cough"],
    bodySystems: ["respiratory"],
    severityHint: "medium",
  },
  {
    key: "runny_nose",
    label: "Runny Nose",
    aliases: ["runny nose", "nose running", "nasal discharge"],
    bodySystems: ["respiratory", "ent"],
    severityHint: "low",
  },
  {
    key: "nasal_congestion",
    label: "Nasal Congestion",
    aliases: ["blocked nose", "stuffy nose", "nasal congestion", "nose blocked"],
    bodySystems: ["respiratory", "ent"],
    severityHint: "low",
  },
  {
    key: "sneezing",
    label: "Sneezing",
    aliases: ["sneezing", "repeated sneezing"],
    bodySystems: ["respiratory", "ent"],
    severityHint: "low",
  },
  {
    key: "sore_throat",
    label: "Sore Throat",
    aliases: ["sore throat", "throat pain", "pain while swallowing", "scratchy throat"],
    bodySystems: ["respiratory", "ent"],
    severityHint: "medium",
  },
  {
    key: "shortness_of_breath",
    label: "Shortness of Breath",
    aliases: ["shortness of breath", "difficulty breathing", "breathing problem", "cannot breathe properly"],
    bodySystems: ["respiratory", "cardiovascular"],
    severityHint: "high",
  },
  {
    key: "wheezing",
    label: "Wheezing",
    aliases: ["wheezing", "whistling while breathing", "chest wheeze"],
    bodySystems: ["respiratory"],
    severityHint: "high",
  },
  {
    key: "chest_pain",
    label: "Chest Pain",
    aliases: ["chest pain", "pain in chest", "tight chest", "chest discomfort"],
    bodySystems: ["cardiovascular", "respiratory"],
    severityHint: "high",
  },
  {
    key: "headache",
    label: "Headache",
    aliases: ["headache", "head pain", "my head hurts", "pressure in head"],
    bodySystems: ["neurological", "general"],
    severityHint: "medium",
  },
  {
    key: "severe_headache",
    label: "Severe Headache",
    aliases: ["severe headache", "intense headache", "worst headache"],
    bodySystems: ["neurological"],
    severityHint: "high",
  },
  {
    key: "light_sensitivity",
    label: "Light Sensitivity",
    aliases: ["light sensitivity", "bright light hurts", "sensitive to light"],
    bodySystems: ["neurological", "eye"],
    severityHint: "medium",
  },
  {
    key: "dizziness",
    label: "Dizziness",
    aliases: ["dizziness", "lightheaded", "feeling dizzy", "vertigo"],
    bodySystems: ["neurological", "cardiovascular", "general"],
    severityHint: "medium",
  },
  {
    key: "fatigue",
    label: "Fatigue",
    aliases: ["fatigue", "tired", "weakness", "low energy", "feeling exhausted"],
    bodySystems: ["general", "endocrine"],
    severityHint: "medium",
  },
  {
    key: "body_ache",
    label: "Body Ache",
    aliases: ["body ache", "body pain", "muscle ache", "body soreness"],
    bodySystems: ["general", "musculoskeletal"],
    severityHint: "medium",
  },
  {
    key: "nausea",
    label: "Nausea",
    aliases: ["nausea", "queasy", "feeling nauseous"],
    bodySystems: ["digestive", "general"],
    severityHint: "medium",
  },
  {
    key: "vomiting",
    label: "Vomiting",
    aliases: ["vomiting", "throwing up", "being sick", "vomit"],
    bodySystems: ["digestive", "general"],
    severityHint: "medium",
  },
  {
    key: "diarrhea",
    label: "Diarrhea",
    aliases: ["diarrhea", "loose motion", "loose stools", "watery stool"],
    bodySystems: ["digestive"],
    severityHint: "medium",
  },
  {
    key: "abdominal_pain",
    label: "Abdominal Pain",
    aliases: ["abdominal pain", "stomach pain", "belly pain", "stomach cramps"],
    bodySystems: ["digestive"],
    severityHint: "medium",
  },
  {
    key: "severe_abdominal_pain",
    label: "Severe Abdominal Pain",
    aliases: ["severe abdominal pain", "severe stomach pain", "sharp belly pain"],
    bodySystems: ["digestive"],
    severityHint: "high",
  },
  {
    key: "acidity",
    label: "Acidity",
    aliases: ["acidity", "acid reflux", "heartburn", "burning chest after food", "burning in stomach"],
    bodySystems: ["digestive"],
    severityHint: "low",
  },
  {
    key: "bloating",
    label: "Bloating",
    aliases: ["bloating", "gas", "gassy", "stomach bloated", "abdomen full"],
    bodySystems: ["digestive"],
    severityHint: "low",
  },
  {
    key: "constipation",
    label: "Constipation",
    aliases: ["constipation", "hard stool", "not passing stool", "difficulty passing stool"],
    bodySystems: ["digestive"],
    severityHint: "medium",
  },
  {
    key: "painful_urination",
    label: "Painful Urination",
    aliases: ["painful urination", "pain while peeing", "pain when urinating"],
    bodySystems: ["urinary"],
    severityHint: "medium",
  },
  {
    key: "frequent_urination",
    label: "Frequent Urination",
    aliases: ["frequent urination", "peeing often", "urinating often"],
    bodySystems: ["urinary", "endocrine"],
    severityHint: "medium",
  },
  {
    key: "burning_urination",
    label: "Burning Urination",
    aliases: ["burning urination", "burning while peeing", "urine burning"],
    bodySystems: ["urinary"],
    severityHint: "medium",
  },
  {
    key: "lower_back_pain",
    label: "Lower Back Pain",
    aliases: ["lower back pain", "pain in lower back", "lower backache"],
    bodySystems: ["musculoskeletal", "urinary"],
    severityHint: "medium",
  },
  {
    key: "back_pain",
    label: "Back Pain",
    aliases: ["back pain", "backache", "pain in back"],
    bodySystems: ["musculoskeletal"],
    severityHint: "medium",
  },
  {
    key: "joint_pain",
    label: "Joint Pain",
    aliases: ["joint pain", "knee pain", "elbow pain", "pain in joints"],
    bodySystems: ["musculoskeletal"],
    severityHint: "medium",
  },
  {
    key: "rash",
    label: "Rash",
    aliases: ["rash", "skin rash", "red spots on skin"],
    bodySystems: ["skin"],
    severityHint: "medium",
  },
  {
    key: "itching",
    label: "Itching",
    aliases: ["itching", "itchy skin", "skin itch"],
    bodySystems: ["skin"],
    severityHint: "medium",
  },
  {
    key: "skin_redness",
    label: "Skin Redness",
    aliases: ["skin redness", "red skin", "inflamed skin"],
    bodySystems: ["skin"],
    severityHint: "medium",
  },
  {
    key: "eye_redness",
    label: "Eye Redness",
    aliases: ["eye redness", "red eye", "eyes are red"],
    bodySystems: ["eye"],
    severityHint: "medium",
  },
  {
    key: "eye_itching",
    label: "Eye Itching",
    aliases: ["itchy eyes", "eye itching", "eyes itching"],
    bodySystems: ["eye"],
    severityHint: "low",
  },
  {
    key: "blurred_vision",
    label: "Blurred Vision",
    aliases: ["blurred vision", "vision blurred", "cannot see clearly"],
    bodySystems: ["eye", "neurological", "endocrine"],
    severityHint: "high",
  },
  {
    key: "ear_pain",
    label: "Ear Pain",
    aliases: ["ear pain", "earache", "pain in ear"],
    bodySystems: ["ent"],
    severityHint: "medium",
  },
  {
    key: "hearing_loss",
    label: "Hearing Loss",
    aliases: ["hearing loss", "reduced hearing", "cannot hear properly"],
    bodySystems: ["ent"],
    severityHint: "medium",
  },
  {
    key: "increased_thirst",
    label: "Increased Thirst",
    aliases: ["increased thirst", "always thirsty", "excessive thirst"],
    bodySystems: ["endocrine", "general"],
    severityHint: "medium",
  },
  {
    key: "weight_loss",
    label: "Weight Loss",
    aliases: ["weight loss", "losing weight", "unexplained weight loss"],
    bodySystems: ["endocrine", "general"],
    severityHint: "medium",
  },
  {
    key: "palpitations",
    label: "Palpitations",
    aliases: ["palpitations", "heart racing", "fast heartbeat", "pounding heart"],
    bodySystems: ["cardiovascular", "endocrine"],
    severityHint: "medium",
  },
  {
    key: "anxiety",
    label: "Anxiety",
    aliases: ["anxiety", "panic", "feeling anxious", "restless", "nervous"],
    bodySystems: ["neurological", "general"],
    severityHint: "medium",
  },
  {
    key: "confusion",
    label: "Confusion",
    aliases: ["confusion", "disoriented", "not thinking clearly"],
    bodySystems: ["neurological"],
    severityHint: "high",
  },
  {
    key: "fainting",
    label: "Fainting",
    aliases: ["fainting", "passed out", "blacked out", "loss of consciousness"],
    bodySystems: ["cardiovascular", "neurological"],
    severityHint: "high",
  },
  {
    key: "seizure",
    label: "Seizure",
    aliases: ["seizure", "fits", "convulsion"],
    bodySystems: ["neurological"],
    severityHint: "high",
  },
  {
    key: "blood_in_vomit",
    label: "Blood in Vomit",
    aliases: ["blood in vomit", "vomiting blood", "throwing up blood"],
    bodySystems: ["digestive"],
    severityHint: "high",
  },
  {
    key: "blood_in_stool",
    label: "Blood in Stool",
    aliases: ["blood in stool", "bloody stool", "blood while passing stool"],
    bodySystems: ["digestive"],
    severityHint: "high",
  },
  {
    key: "vision_loss",
    label: "Vision Loss",
    aliases: ["vision loss", "sudden loss of vision", "cannot see from one eye"],
    bodySystems: ["eye", "neurological"],
    severityHint: "high",
  },
];

const redFlagCatalog = [
  {
    key: "chest_pain",
    label: "Chest pain",
    aliases: ["chest pain", "tight chest", "pain in chest"],
    urgency: "emergency",
    message: "Chest pain can be serious. Seek immediate medical care.",
  },
  {
    key: "shortness_of_breath",
    label: "Shortness of breath",
    aliases: ["shortness of breath", "difficulty breathing", "cannot breathe properly"],
    urgency: "emergency",
    message: "Breathing difficulty needs urgent medical attention.",
  },
  {
    key: "confusion",
    label: "Confusion",
    aliases: ["confusion", "disoriented", "not thinking clearly"],
    urgency: "emergency",
    message: "Sudden confusion needs urgent medical evaluation.",
  },
  {
    key: "fainting",
    label: "Fainting",
    aliases: ["fainting", "passed out", "blacked out"],
    urgency: "emergency",
    message: "Fainting should be assessed urgently, especially if unexplained.",
  },
  {
    key: "seizure",
    label: "Seizure",
    aliases: ["seizure", "fits", "convulsion"],
    urgency: "emergency",
    message: "A seizure requires immediate medical help.",
  },
  {
    key: "blood_in_vomit",
    label: "Blood in vomit",
    aliases: ["blood in vomit", "vomiting blood", "throwing up blood"],
    urgency: "emergency",
    message: "Blood in vomit is an emergency symptom.",
  },
  {
    key: "blood_in_stool",
    label: "Blood in stool",
    aliases: ["blood in stool", "bloody stool"],
    urgency: "emergency",
    message: "Blood in stool needs urgent medical review.",
  },
  {
    key: "sudden_worst_headache",
    label: "Sudden severe headache",
    aliases: ["sudden worst headache", "worst headache of my life", "sudden severe headache"],
    urgency: "emergency",
    message: "A sudden severe headache can be dangerous and needs urgent care.",
  },
  {
    key: "vision_loss",
    label: "Vision loss",
    aliases: ["vision loss", "sudden loss of vision", "cannot see from one eye"],
    urgency: "emergency",
    message: "Sudden vision loss requires emergency evaluation.",
  },
  {
    key: "severe_abdominal_pain",
    label: "Severe abdominal pain",
    aliases: ["severe abdominal pain", "sharp belly pain", "severe stomach pain"],
    urgency: "emergency",
    message: "Severe abdominal pain can require urgent medical attention.",
  },
  {
    key: "persistent_high_fever",
    label: "Persistent high fever",
    aliases: ["persistent high fever", "high fever for 3 days", "fever not going down"],
    urgency: "urgent",
    message: "A persistent high fever should be assessed by a doctor quickly.",
  },
  {
    key: "blue_lips",
    label: "Blue lips",
    aliases: ["blue lips", "lips turning blue"],
    urgency: "emergency",
    message: "Blue lips can signal low oxygen and need emergency care.",
  },
  {
    key: "one_sided_weakness",
    label: "One-sided weakness",
    aliases: ["one sided weakness", "weakness on one side", "one arm weak"],
    urgency: "emergency",
    message: "One-sided weakness may be a medical emergency.",
  },
  {
    key: "pregnancy_bleeding",
    label: "Pregnancy bleeding",
    aliases: ["pregnancy bleeding", "bleeding during pregnancy"],
    urgency: "emergency",
    message: "Bleeding during pregnancy should be assessed immediately.",
  },
  {
    key: "uncontrolled_vomiting",
    label: "Uncontrolled vomiting",
    aliases: ["uncontrolled vomiting", "vomiting continuously", "cannot stop vomiting"],
    urgency: "urgent",
    message: "Repeated vomiting can quickly lead to dehydration and needs urgent care.",
  },
];

const conditionCatalog = [
  {
    key: "common_cold",
    name: "Common Cold",
    bodySystems: ["respiratory", "ent"],
    symptomWeights: { runny_nose: 4, sneezing: 4, sore_throat: 2, nasal_congestion: 3, cough: 2, fever: 1 },
    requiredAny: ["runny_nose", "sneezing", "nasal_congestion"],
    optionalBoost: ["sore_throat", "cough"],
    negativeSignals: ["chest_pain", "blurred_vision"],
    severity: "low",
    urgency: "routine",
    otcMedicines: ["Cetirizine", "Paracetamol if fever is present"],
    homeAdvice: ["Drink warm fluids", "Rest well", "Try steam inhalation if congested"],
    specialist: "General Physician",
  },
  {
    key: "viral_flu",
    name: "Viral Flu",
    bodySystems: ["general", "respiratory"],
    symptomWeights: { fever: 4, chills: 3, body_ache: 4, fatigue: 3, cough: 2, headache: 2, sore_throat: 2 },
    requiredAny: ["fever", "body_ache"],
    optionalBoost: ["chills", "fatigue"],
    negativeSignals: ["itching", "burning_urination"],
    severity: "medium",
    urgency: "routine",
    otcMedicines: ["Paracetamol", "ORS or fluids"],
    homeAdvice: ["Hydrate well", "Rest", "Monitor fever and breathing"],
    specialist: "General Physician",
  },
  {
    key: "allergic_rhinitis",
    name: "Allergic Rhinitis",
    bodySystems: ["respiratory", "ent"],
    symptomWeights: { sneezing: 4, runny_nose: 4, nasal_congestion: 3, eye_itching: 3, headache: 1 },
    requiredAny: ["sneezing", "runny_nose"],
    optionalBoost: ["eye_itching", "nasal_congestion"],
    negativeSignals: ["fever", "high_fever"],
    severity: "low",
    urgency: "routine",
    otcMedicines: ["Cetirizine", "Saline nasal rinse"],
    homeAdvice: ["Reduce dust or allergy exposure", "Wash face after outdoor exposure"],
    specialist: "ENT Specialist",
  },
  {
    key: "sinusitis",
    name: "Sinusitis",
    bodySystems: ["ent", "respiratory"],
    symptomWeights: { nasal_congestion: 4, headache: 3, sore_throat: 1, fever: 2, cough: 1 },
    requiredAny: ["nasal_congestion", "headache"],
    optionalBoost: ["fever"],
    negativeSignals: ["burning_urination"],
    severity: "medium",
    urgency: "routine",
    otcMedicines: ["Paracetamol", "Saline spray"],
    homeAdvice: ["Use steam inhalation", "Hydrate", "Rest and monitor symptoms"],
    specialist: "ENT Specialist",
  },
  {
    key: "pharyngitis",
    name: "Pharyngitis / Throat Infection",
    bodySystems: ["ent"],
    symptomWeights: { sore_throat: 5, fever: 2, headache: 1, cough: 1 },
    requiredAny: ["sore_throat"],
    optionalBoost: ["fever"],
    negativeSignals: ["itching", "rash"],
    severity: "medium",
    urgency: "routine",
    otcMedicines: ["Paracetamol", "Warm salt-water gargles"],
    homeAdvice: ["Avoid very cold drinks", "Rest voice", "Stay hydrated"],
    specialist: "ENT Specialist",
  },
  {
    key: "bronchitis",
    name: "Bronchitis Pattern",
    bodySystems: ["respiratory"],
    symptomWeights: { cough: 4, productive_cough: 3, fever: 1, shortness_of_breath: 2, fatigue: 1 },
    requiredAny: ["cough", "productive_cough"],
    optionalBoost: ["shortness_of_breath"],
    negativeSignals: ["itching"],
    severity: "medium",
    urgency: "routine",
    otcMedicines: ["Paracetamol", "Warm fluids"],
    homeAdvice: ["Avoid smoke exposure", "Rest", "Seek care if breathing worsens"],
    specialist: "Pulmonologist",
  },
  {
    key: "mild_asthma_flare",
    name: "Mild Asthma Flare",
    bodySystems: ["respiratory"],
    symptomWeights: { shortness_of_breath: 5, wheezing: 5, cough: 2, chest_pain: 1 },
    requiredAny: ["shortness_of_breath", "wheezing"],
    optionalBoost: ["cough"],
    negativeSignals: ["vomiting"],
    severity: "high",
    urgency: "urgent",
    otcMedicines: ["No OTC medicine is preferred without prior doctor advice"],
    homeAdvice: ["Use prescribed rescue inhaler if available", "Avoid triggers", "Seek urgent care if symptoms do not settle"],
    specialist: "Pulmonologist",
  },
  {
    key: "gerd",
    name: "Acid Reflux / GERD Pattern",
    bodySystems: ["digestive"],
    symptomWeights: { acidity: 5, bloating: 2, nausea: 1, cough: 1, sore_throat: 1 },
    requiredAny: ["acidity"],
    optionalBoost: ["bloating", "nausea"],
    negativeSignals: ["rash"],
    severity: "low",
    urgency: "routine",
    otcMedicines: ["Antacid such as Digene"],
    homeAdvice: ["Avoid spicy or oily food", "Do not lie down immediately after meals"],
    specialist: "Gastroenterologist",
  },
  {
    key: "gastritis",
    name: "Gastritis Pattern",
    bodySystems: ["digestive"],
    symptomWeights: { acidity: 3, abdominal_pain: 3, bloating: 2, nausea: 2, vomiting: 1 },
    requiredAny: ["abdominal_pain", "acidity"],
    optionalBoost: ["nausea", "bloating"],
    negativeSignals: ["rash", "eye_redness"],
    severity: "medium",
    urgency: "routine",
    otcMedicines: ["Antacid such as Digene", "ORS if vomiting occurs"],
    homeAdvice: ["Eat light meals", "Avoid alcohol and very spicy food", "Hydrate"],
    specialist: "Gastroenterologist",
  },
  {
    key: "food_poisoning",
    name: "Food Poisoning Pattern",
    bodySystems: ["digestive"],
    symptomWeights: { vomiting: 4, diarrhea: 4, abdominal_pain: 3, nausea: 3, fever: 2 },
    requiredAny: ["vomiting", "diarrhea"],
    optionalBoost: ["abdominal_pain", "fever"],
    negativeSignals: ["itching"],
    severity: "medium",
    urgency: "routine",
    otcMedicines: ["ORS", "Paracetamol for fever if needed"],
    homeAdvice: ["Use oral rehydration", "Avoid heavy foods", "Seek care if dehydration worsens"],
    specialist: "General Physician",
  },
  {
    key: "viral_gastroenteritis",
    name: "Viral Gastroenteritis",
    bodySystems: ["digestive", "general"],
    symptomWeights: { diarrhea: 4, vomiting: 3, nausea: 3, fever: 2, fatigue: 2, abdominal_pain: 2 },
    requiredAny: ["diarrhea", "vomiting"],
    optionalBoost: ["fever", "fatigue"],
    negativeSignals: ["itching", "eye_redness"],
    severity: "medium",
    urgency: "routine",
    otcMedicines: ["ORS", "Paracetamol if fever is present"],
    homeAdvice: ["Hydrate aggressively", "Eat bland foods", "Monitor for dehydration"],
    specialist: "General Physician",
  },
  {
    key: "constipation_pattern",
    name: "Constipation Pattern",
    bodySystems: ["digestive"],
    symptomWeights: { constipation: 5, bloating: 2, abdominal_pain: 2, nausea: 1 },
    requiredAny: ["constipation"],
    optionalBoost: ["bloating"],
    negativeSignals: ["diarrhea"],
    severity: "low",
    urgency: "routine",
    otcMedicines: ["Fiber supplement or doctor-advised laxative"],
    homeAdvice: ["Drink more water", "Increase fiber intake", "Walk regularly"],
    specialist: "Gastroenterologist",
  },
  {
    key: "migraine",
    name: "Migraine",
    bodySystems: ["neurological"],
    symptomWeights: { headache: 4, severe_headache: 5, nausea: 2, vomiting: 2, light_sensitivity: 4, blurred_vision: 2 },
    requiredAny: ["headache", "severe_headache"],
    optionalBoost: ["light_sensitivity", "nausea"],
    negativeSignals: ["runny_nose", "sneezing"],
    severity: "medium",
    urgency: "routine",
    otcMedicines: ["Paracetamol", "Ibuprofen if tolerated"],
    homeAdvice: ["Rest in a dark quiet room", "Hydrate", "Reduce known triggers"],
    specialist: "Neurologist",
  },
  {
    key: "tension_headache",
    name: "Tension Headache",
    bodySystems: ["neurological"],
    symptomWeights: { headache: 4, fatigue: 2, anxiety: 2 },
    requiredAny: ["headache"],
    optionalBoost: ["fatigue", "anxiety"],
    negativeSignals: ["runny_nose", "vomiting"],
    severity: "low",
    urgency: "routine",
    otcMedicines: ["Paracetamol"],
    homeAdvice: ["Rest", "Stretch gently", "Reduce stress and screen strain"],
    specialist: "General Physician",
  },
  {
    key: "dehydration",
    name: "Dehydration Pattern",
    bodySystems: ["general", "digestive"],
    symptomWeights: { dizziness: 3, fatigue: 3, increased_thirst: 4, vomiting: 1, diarrhea: 1 },
    requiredAny: ["increased_thirst", "dizziness"],
    optionalBoost: ["fatigue"],
    negativeSignals: ["rash"],
    severity: "medium",
    urgency: "routine",
    otcMedicines: ["ORS"],
    homeAdvice: ["Increase fluids", "Take oral rehydration solution", "Rest in a cool place"],
    specialist: "General Physician",
  },
  {
    key: "uti",
    name: "Urinary Tract Infection Pattern",
    bodySystems: ["urinary"],
    symptomWeights: { painful_urination: 4, burning_urination: 5, frequent_urination: 4, lower_back_pain: 2, fever: 1 },
    requiredAny: ["burning_urination", "painful_urination", "frequent_urination"],
    optionalBoost: ["lower_back_pain"],
    negativeSignals: ["cough", "sneezing"],
    severity: "medium",
    urgency: "routine",
    otcMedicines: ["Hydration only until doctor review"],
    homeAdvice: ["Drink plenty of water", "Do not hold urine", "Seek clinician review if fever or back pain is present"],
    specialist: "Urologist",
  },
  {
    key: "conjunctivitis",
    name: "Conjunctivitis Pattern",
    bodySystems: ["eye"],
    symptomWeights: { eye_redness: 5, eye_itching: 3, blurred_vision: 1 },
    requiredAny: ["eye_redness", "eye_itching"],
    optionalBoost: ["blurred_vision"],
    negativeSignals: ["vomiting", "diarrhea"],
    severity: "low",
    urgency: "routine",
    otcMedicines: ["Lubricating eye drops if previously advised"],
    homeAdvice: ["Avoid rubbing eyes", "Use clean towels", "Maintain hygiene"],
    specialist: "Ophthalmologist",
  },
  {
    key: "ear_infection",
    name: "Ear Infection Pattern",
    bodySystems: ["ent"],
    symptomWeights: { ear_pain: 5, fever: 2, hearing_loss: 2, sore_throat: 1 },
    requiredAny: ["ear_pain"],
    optionalBoost: ["fever", "hearing_loss"],
    negativeSignals: ["acidity"],
    severity: "medium",
    urgency: "routine",
    otcMedicines: ["Paracetamol for pain"],
    homeAdvice: ["Keep ear dry", "Avoid inserting objects into the ear"],
    specialist: "ENT Specialist",
  },
  {
    key: "fungal_skin_infection",
    name: "Fungal Skin Infection Pattern",
    bodySystems: ["skin"],
    symptomWeights: { rash: 3, itching: 4, skin_redness: 2 },
    requiredAny: ["itching", "rash"],
    optionalBoost: ["skin_redness"],
    negativeSignals: ["fever", "cough"],
    severity: "low",
    urgency: "routine",
    otcMedicines: ["Clotrimazole cream"],
    homeAdvice: ["Keep skin dry", "Avoid sharing towels", "Wear breathable clothing"],
    specialist: "Dermatologist",
  },
  {
    key: "contact_dermatitis",
    name: "Contact Dermatitis Pattern",
    bodySystems: ["skin"],
    symptomWeights: { rash: 3, itching: 4, skin_redness: 4 },
    requiredAny: ["rash", "itching"],
    optionalBoost: ["skin_redness"],
    negativeSignals: ["vomiting", "diarrhea"],
    severity: "low",
    urgency: "routine",
    otcMedicines: ["Calamine lotion", "Cetirizine if itching is significant"],
    homeAdvice: ["Avoid the triggering product", "Use cool compresses", "Keep the area clean"],
    specialist: "Dermatologist",
  },
  {
    key: "hypertension_pattern",
    name: "Hypertension Warning Pattern",
    bodySystems: ["cardiovascular"],
    symptomWeights: { headache: 2, dizziness: 2, chest_pain: 2, blurred_vision: 2, palpitations: 2 },
    requiredAny: ["headache", "dizziness", "palpitations"],
    optionalBoost: ["blurred_vision"],
    negativeSignals: ["runny_nose", "itching"],
    severity: "medium",
    urgency: "routine",
    otcMedicines: ["No OTC medicine is preferred without blood pressure evaluation"],
    homeAdvice: ["Check blood pressure if possible", "Reduce salt intake", "Seek evaluation if recurring"],
    specialist: "Cardiologist",
  },
  {
    key: "hypotension_pattern",
    name: "Low Blood Pressure Pattern",
    bodySystems: ["cardiovascular"],
    symptomWeights: { dizziness: 4, fainting: 4, fatigue: 2, nausea: 1 },
    requiredAny: ["dizziness", "fainting"],
    optionalBoost: ["fatigue"],
    negativeSignals: ["rash"],
    severity: "medium",
    urgency: "urgent",
    otcMedicines: ["Oral fluids or ORS"],
    homeAdvice: ["Lie down safely", "Hydrate", "Seek review if episodes repeat"],
    specialist: "Cardiologist",
  },
  {
    key: "anemia_pattern",
    name: "Anemia Pattern",
    bodySystems: ["general"],
    symptomWeights: { fatigue: 4, dizziness: 3, shortness_of_breath: 2, palpitations: 2, headache: 1 },
    requiredAny: ["fatigue", "dizziness"],
    optionalBoost: ["palpitations"],
    negativeSignals: ["runny_nose", "itching"],
    severity: "medium",
    urgency: "routine",
    otcMedicines: ["Iron supplements only if previously advised"],
    homeAdvice: ["Seek blood testing", "Maintain a balanced diet with iron-rich foods"],
    specialist: "General Physician",
  },
  {
    key: "diabetes_warning_pattern",
    name: "Diabetes Warning Pattern",
    bodySystems: ["endocrine"],
    symptomWeights: { increased_thirst: 4, frequent_urination: 4, fatigue: 2, blurred_vision: 2, weight_loss: 3 },
    requiredAny: ["increased_thirst", "frequent_urination"],
    optionalBoost: ["weight_loss", "blurred_vision"],
    negativeSignals: ["runny_nose"],
    severity: "medium",
    urgency: "routine",
    otcMedicines: ["No OTC medicine is recommended without clinician assessment"],
    homeAdvice: ["Arrange blood sugar testing", "Stay hydrated", "Do not delay evaluation if symptoms persist"],
    specialist: "Endocrinologist",
  },
  {
    key: "thyroid_imbalance_pattern",
    name: "Thyroid Imbalance Pattern",
    bodySystems: ["endocrine"],
    symptomWeights: { fatigue: 3, weight_loss: 2, palpitations: 2, anxiety: 2 },
    requiredAny: ["fatigue", "palpitations", "weight_loss"],
    optionalBoost: ["anxiety"],
    negativeSignals: ["productive_cough"],
    severity: "medium",
    urgency: "routine",
    otcMedicines: ["No OTC medicine is recommended without thyroid testing"],
    homeAdvice: ["Arrange thyroid testing", "Track energy and weight changes"],
    specialist: "Endocrinologist",
  },
  {
    key: "muscle_strain",
    name: "Muscle Strain",
    bodySystems: ["musculoskeletal"],
    symptomWeights: { back_pain: 4, lower_back_pain: 4, body_ache: 2, joint_pain: 1 },
    requiredAny: ["back_pain", "lower_back_pain"],
    optionalBoost: ["body_ache"],
    negativeSignals: ["burning_urination"],
    severity: "low",
    urgency: "routine",
    otcMedicines: ["Topical pain relief gel", "Paracetamol"],
    homeAdvice: ["Rest the affected area", "Use gentle stretching", "Avoid heavy lifting"],
    specialist: "Orthopedic",
  },
  {
    key: "arthritis_pattern",
    name: "Joint Inflammation Pattern",
    bodySystems: ["musculoskeletal"],
    symptomWeights: { joint_pain: 5, fatigue: 1, body_ache: 1 },
    requiredAny: ["joint_pain"],
    optionalBoost: ["fatigue"],
    negativeSignals: ["runny_nose"],
    severity: "medium",
    urgency: "routine",
    otcMedicines: ["Topical pain relief gel", "Paracetamol"],
    homeAdvice: ["Avoid overuse", "Use joint support if helpful", "Seek review if persistent"],
    specialist: "Orthopedic",
  },
  {
    key: "dengue_like_fever_pattern",
    name: "Dengue-like Fever Pattern",
    bodySystems: ["general"],
    symptomWeights: { high_fever: 5, body_ache: 4, severe_headache: 3, nausea: 2, rash: 2, vomiting: 2 },
    requiredAny: ["high_fever", "body_ache"],
    optionalBoost: ["rash", "nausea"],
    negativeSignals: ["runny_nose", "sneezing"],
    severity: "high",
    urgency: "urgent",
    otcMedicines: ["Paracetamol only until clinician review"],
    homeAdvice: ["Hydrate", "Avoid ibuprofen unless a doctor advises it", "Seek prompt medical testing"],
    specialist: "General Physician",
  },
  {
    key: "heat_exhaustion",
    name: "Heat Exhaustion Pattern",
    bodySystems: ["general"],
    symptomWeights: { dizziness: 3, fatigue: 3, increased_thirst: 4, headache: 2, nausea: 2 },
    requiredAny: ["increased_thirst", "dizziness"],
    optionalBoost: ["nausea", "fatigue"],
    negativeSignals: ["runny_nose"],
    severity: "medium",
    urgency: "routine",
    otcMedicines: ["ORS"],
    homeAdvice: ["Move to a cool place", "Hydrate", "Rest and monitor body temperature"],
    specialist: "General Physician",
  },
  {
    key: "panic_anxiety_pattern",
    name: "Panic / Anxiety Episode Pattern",
    bodySystems: ["neurological", "general"],
    symptomWeights: { anxiety: 5, palpitations: 3, dizziness: 2, shortness_of_breath: 2, chest_pain: 1 },
    requiredAny: ["anxiety", "palpitations"],
    optionalBoost: ["dizziness", "shortness_of_breath"],
    negativeSignals: ["productive_cough", "burning_urination"],
    severity: "medium",
    urgency: "routine",
    otcMedicines: ["No OTC medicine is recommended without a doctor review"],
    homeAdvice: ["Slow breathing exercises can help", "Move to a calm environment", "Seek mental health support if frequent"],
    specialist: "General Physician",
  },
];

const bodySystemGuidance = {
  general: {
    specialist: "General Physician",
    advice: [
      "Monitor your symptoms closely.",
      "Use rest and hydration as first-line support when appropriate.",
      "Seek medical review if symptoms persist or worsen.",
    ],
  },
  respiratory: {
    specialist: "Pulmonologist",
    advice: [
      "Monitor breathing difficulty carefully.",
      "Warm fluids and steam inhalation may help with mild congestion.",
      "Seek urgent review if breathing becomes difficult.",
    ],
  },
  digestive: {
    specialist: "Gastroenterologist",
    advice: [
      "Prefer light meals and good hydration.",
      "Avoid oily, spicy, or very heavy foods while symptoms are active.",
      "Seek care if pain, vomiting, or dehydration worsens.",
    ],
  },
  neurological: {
    specialist: "Neurologist",
    advice: [
      "Rest in a calm environment and avoid overexertion.",
      "Watch for confusion, severe headache, or worsening symptoms.",
      "Seek review if symptoms are persistent or progressive.",
    ],
  },
  cardiovascular: {
    specialist: "Cardiologist",
    advice: [
      "Avoid heavy exertion until symptoms are better understood.",
      "Monitor for dizziness, chest discomfort, or palpitations.",
      "Seek urgent care if symptoms become severe or sudden.",
    ],
  },
  urinary: {
    specialist: "Urologist",
    advice: [
      "Maintain good hydration.",
      "Do not ignore pain or burning during urination.",
      "Seek care sooner if fever or back pain is also present.",
    ],
  },
  skin: {
    specialist: "Dermatologist",
    advice: [
      "Keep the affected area clean and dry.",
      "Avoid known triggers or irritating products.",
      "Seek review if rash spreads or becomes painful.",
    ],
  },
  eye: {
    specialist: "Ophthalmologist",
    advice: [
      "Avoid rubbing the eyes.",
      "Maintain hygiene and avoid sharing towels.",
      "Seek urgent review if vision changes appear.",
    ],
  },
  ent: {
    specialist: "ENT Specialist",
    advice: [
      "Use warm fluids and gentle supportive care where appropriate.",
      "Watch for persistent pain, discharge, or fever.",
      "Seek review if symptoms are not settling.",
    ],
  },
  endocrine: {
    specialist: "Endocrinologist",
    advice: [
      "Track symptom pattern, appetite, and weight changes.",
      "Arrange clinician review for hormone-related concerns.",
      "Do not self-medicate without proper testing.",
    ],
  },
  musculoskeletal: {
    specialist: "Orthopedic",
    advice: [
      "Avoid overuse of painful joints or muscles.",
      "Use rest and posture correction where appropriate.",
      "Seek review if pain persists or limits movement.",
    ],
  },
};

module.exports = {
  symptomCatalog,
  redFlagCatalog,
  conditionCatalog,
  bodySystemGuidance,
};
