const doctors = [
  {
    id: "doc-sarah-johnson",
    name: "Dr. Sarah Johnson",
    specialty: "Cardiologist",
    location: "New York, NY",
    clinic: "Heart Care Center",
    exp: "12 Yrs",
    rating: 4.8,
    about: "Cardiology specialist focused on preventive heart care and long-term treatment planning.",
    availableSlots: ["09:00 AM", "10:30 AM", "12:00 PM", "04:00 PM", "05:30 PM"],
  },
  {
    id: "doc-michael-chen",
    name: "Dr. Michael Chen",
    specialty: "Dermatologist",
    location: "San Francisco, CA",
    clinic: "Skin Health Clinic",
    exp: "8 Yrs",
    rating: 4.9,
    about: "Treats acne, eczema, chronic skin conditions, and preventive skin screenings.",
    availableSlots: ["09:00 AM", "10:30 AM", "12:00 PM", "04:00 PM", "05:30 PM"],
  },
  {
    id: "doc-emily-davis",
    name: "Dr. Emily Davis",
    specialty: "Pediatrician",
    location: "Chicago, IL",
    clinic: "Children First Hospital",
    exp: "15 Yrs",
    rating: 4.7,
    about: "Family-centered pediatric specialist experienced in routine and urgent child care.",
    availableSlots: ["09:00 AM", "10:30 AM", "12:00 PM", "04:00 PM", "05:30 PM"],
  },
  {
    id: "doc-james-wilson",
    name: "Dr. James Wilson",
    specialty: "Neurologist",
    location: "Houston, TX",
    clinic: "NeuroCare Institute",
    exp: "20 Yrs",
    rating: 4.9,
    about: "Works on headaches, migraines, nerve disorders, and complex neurological conditions.",
    availableSlots: ["09:00 AM", "10:30 AM", "12:00 PM", "04:00 PM", "05:30 PM"],
  },
  {
    id: "doc-linda-martinez",
    name: "Dr. Linda Martinez",
    specialty: "General Physician",
    location: "Miami, FL",
    clinic: "Martinez Family Clinic",
    exp: "6 Yrs",
    rating: 4.6,
    about: "Primary care physician for day-to-day concerns, follow-ups, and wellness visits.",
    availableSlots: ["09:00 AM", "10:30 AM", "12:00 PM", "04:00 PM", "05:30 PM"],
  },
  {
    id: "doc-raj-patel",
    name: "Dr. Raj Patel",
    specialty: "Orthopedic",
    location: "Austin, TX",
    clinic: "Motion Orthopedic Center",
    exp: "18 Yrs",
    rating: 4.9,
    about: "Orthopedic specialist helping patients manage injury recovery and chronic joint pain.",
    availableSlots: ["09:00 AM", "10:30 AM", "12:00 PM", "04:00 PM", "05:30 PM"],
  },
  {
    id: "doc-neha-gupta",
    name: "Dr. Neha Gupta",
    specialty: "Gastroenterologist",
    location: "Seattle, WA",
    clinic: "Digestive Health Associates",
    exp: "11 Yrs",
    rating: 4.8,
    about: "Helps patients with stomach pain, acidity, indigestion, and longer-term digestive issues.",
    availableSlots: ["09:00 AM", "10:30 AM", "12:00 PM", "04:00 PM", "05:30 PM"],
  },
  {
    id: "doc-aaron-kelly",
    name: "Dr. Aaron Kelly",
    specialty: "Dentist",
    location: "Boston, MA",
    clinic: "Bright Smile Dental",
    exp: "9 Yrs",
    rating: 4.7,
    about: "Handles emergency tooth pain, preventive care, and long-term dental treatment plans.",
    availableSlots: ["09:00 AM", "10:30 AM", "12:00 PM", "04:00 PM", "05:30 PM"],
  },
];

const symptoms = [
  {
    id: "sym-fever",
    symptom: "Fever",
    keywords: ["fever", "temperature", "high temp"],
    medicine: "Paracetamol (Dolo 650)",
    advice: "Stay hydrated, rest well, and monitor your temperature. Seek a doctor if it stays high or lasts more than two days.",
    doctorType: "General Physician",
    severity: "Monitor closely",
  },
  {
    id: "sym-headache",
    symptom: "Headache",
    keywords: ["headache", "migraine", "head pain"],
    medicine: "Ibuprofen or Paracetamol",
    advice: "Rest in a quiet room, reduce screen time, and drink water. If pain is severe or frequent, consult a neurologist.",
    doctorType: "Neurologist",
    severity: "Usually manageable",
  },
  {
    id: "sym-cold",
    symptom: "Cold / Runny Nose",
    keywords: ["cold", "runny nose", "sneezing"],
    medicine: "Cetirizine or Vitamin C",
    advice: "Steam inhalation, warm fluids, and rest usually help. Watch for breathing difficulty or worsening symptoms.",
    doctorType: "General Physician",
    severity: "Usually manageable",
  },
  {
    id: "sym-acidity",
    symptom: "Acidity",
    keywords: ["acidity", "acid reflux", "heartburn"],
    medicine: "Antacid such as Digene",
    advice: "Avoid spicy food, eat smaller meals, and do not lie down right after eating.",
    doctorType: "Gastroenterologist",
    severity: "Monitor diet-related triggers",
  },
  {
    id: "sym-stomach-pain",
    symptom: "Stomach Pain",
    keywords: ["stomach pain", "abdominal pain", "cramps"],
    medicine: "Meftal-Spas or doctor-advised antispasmodic",
    advice: "Eat light meals, stay hydrated, and seek care quickly if the pain is severe or persistent.",
    doctorType: "Gastroenterologist",
    severity: "Needs attention if persistent",
  },
  {
    id: "sym-back-pain",
    symptom: "Back Pain",
    keywords: ["back pain", "lower back pain", "backache"],
    medicine: "Topical pain relief gel or doctor-advised NSAID",
    advice: "Avoid heavy lifting, improve posture, and use light stretching if it feels safe.",
    doctorType: "Orthopedic",
    severity: "Monitor mobility and pain level",
  },
  {
    id: "sym-toothache",
    symptom: "Toothache",
    keywords: ["toothache", "tooth pain", "gum pain"],
    medicine: "Pain relief only as advised until dental review",
    advice: "Avoid very hot or cold foods and arrange a dental visit soon, especially if there is swelling.",
    doctorType: "Dentist",
    severity: "Needs dental review",
  },
];

const defaultUser = {
  name: "Demo Patient",
  email: "demo@smartmed.app",
  password: "Demo@12345",
  phone: "+1 555 0100",
  age: 28,
  gender: "Male",
  bloodGroup: "O+",
  address: "123 Health Street, Wellness City, NY",
};

const starterReports = [
  {
    title: "Annual Wellness Summary",
    date: "2026-01-10",
    doctorName: "Dr. Linda Martinez",
    type: "Checkup",
    status: "Ready",
  },
  {
    title: "General Blood Count (CBC)",
    date: "2026-02-05",
    doctorName: "Dr. Sarah Johnson",
    type: "Lab Report",
    status: "Ready",
  },
  {
    title: "Skin Allergy Screening",
    date: "2026-02-18",
    doctorName: "Dr. Michael Chen",
    type: "Lab Report",
    status: "Processing",
  },
];

const starterAppointments = [
  {
    doctorId: "doc-linda-martinez",
    date: "2026-01-10",
    time: "10:30 AM",
    status: "Completed",
  },
  {
    doctorId: "doc-sarah-johnson",
    date: "2026-04-15",
    time: "04:00 PM",
    status: "Upcoming",
  },
];

module.exports = {
  doctors,
  symptoms,
  defaultUser,
  starterReports,
  starterAppointments,
};
