const doctors = [
  {
    id: "doc-kavita-shah",
    name: "Dr. Kavita Shah",
    specialty: "General Physician",
    location: "Surat, Gujarat",
    clinic: "Adajan Wellness Clinic",
    exp: "14 Yrs",
    rating: 4.8,
    about: "Primary care physician in Adajan treating fevers, infections, and everyday family health concerns.",
    availableSlots: ["09:30 AM", "11:00 AM", "01:00 PM", "05:00 PM", "06:30 PM"],
  },
  {
    id: "doc-mehul-desai",
    name: "Dr. Mehul Desai",
    specialty: "Cardiologist",
    location: "Surat, Gujarat",
    clinic: "Vesu Heart Institute",
    exp: "17 Yrs",
    rating: 4.9,
    about: "Cardiologist in Vesu specializing in hypertension management and preventive cardiac screening.",
    availableSlots: ["10:00 AM", "11:30 AM", "03:00 PM", "04:30 PM", "06:00 PM"],
  },
  {
    id: "doc-priya-agarwal",
    name: "Dr. Priya Agarwal",
    specialty: "Dermatologist",
    location: "Surat, Gujarat",
    clinic: "City Light Skin & Hair Clinic",
    exp: "10 Yrs",
    rating: 4.7,
    about: "Dermatologist near City Light treating acne, pigmentation, and hair fall concerns.",
    availableSlots: ["09:00 AM", "12:00 PM", "02:30 PM", "04:00 PM", "05:30 PM"],
  },
  {
    id: "doc-nilesh-patel",
    name: "Dr. Nilesh Patel",
    specialty: "Orthopedic",
    location: "Surat, Gujarat",
    clinic: "Piplod Bone & Joint Center",
    exp: "16 Yrs",
    rating: 4.8,
    about: "Orthopedic surgeon in Piplod focused on sports injuries and joint replacement care.",
    availableSlots: ["09:00 AM", "10:30 AM", "01:30 PM", "03:30 PM", "05:00 PM"],
  },
  {
    id: "doc-riya-mehta",
    name: "Dr. Riya Mehta",
    specialty: "Pediatrician",
    location: "Surat, Gujarat",
    clinic: "Athwalines Child Care",
    exp: "9 Yrs",
    rating: 4.9,
    about: "Pediatrician in Athwalines offering routine vaccination schedules and urgent child care visits.",
    availableSlots: ["09:30 AM", "11:00 AM", "12:30 PM", "04:00 PM", "05:30 PM"],
  },
  {
    id: "doc-sanjay-joshi",
    name: "Dr. Sanjay Joshi",
    specialty: "Gastroenterologist",
    location: "Surat, Gujarat",
    clinic: "Ghod Dod Road Digestive Care",
    exp: "13 Yrs",
    rating: 4.6,
    about: "Gastroenterologist on Ghod Dod Road treating acidity, IBS, and chronic digestive issues.",
    availableSlots: ["10:00 AM", "11:30 AM", "02:00 PM", "04:30 PM", "06:00 PM"],
  },
  {
    id: "doc-rohan-trivedi",
    name: "Dr. Rohan Trivedi",
    specialty: "Dentist",
    location: "Surat, Gujarat",
    clinic: "Vesu Dental Studio",
    exp: "8 Yrs",
    rating: 4.7,
    about: "Handles emergency tooth pain, preventive care, and long-term dental treatment plans in Vesu.",
    availableSlots: ["09:00 AM", "10:30 AM", "12:00 PM", "04:00 PM", "05:30 PM"],
  },
  {
    id: "doc-anjali-rao",
    name: "Dr. Anjali Rao",
    specialty: "Neurologist",
    location: "Ahmedabad, Gujarat",
    clinic: "SG Highway Neuro Center",
    exp: "19 Yrs",
    rating: 4.9,
    about: "Neurologist specializing in migraines, epilepsy, and nerve-related disorders.",
    availableSlots: ["09:00 AM", "10:30 AM", "12:00 PM", "03:00 PM", "05:00 PM"],
  },
  {
    id: "doc-pooja-bhatt",
    name: "Dr. Pooja Bhatt",
    specialty: "Pediatrician",
    location: "Vadodara, Gujarat",
    clinic: "Alkapuri Child Care",
    exp: "11 Yrs",
    rating: 4.8,
    about: "Pediatrician in Alkapuri covering growth check-ups, vaccinations, and childhood illnesses.",
    availableSlots: ["09:00 AM", "10:30 AM", "01:00 PM", "04:00 PM", "05:30 PM"],
  },
  {
    id: "doc-ramesh-iyer",
    name: "Dr. Ramesh Iyer",
    specialty: "Gastroenterologist",
    location: "Rajkot, Gujarat",
    clinic: "Kalawad Road Digestive Clinic",
    exp: "15 Yrs",
    rating: 4.7,
    about: "Gastroenterologist treating acidity, IBS, and liver-related concerns in Rajkot.",
    availableSlots: ["10:00 AM", "11:30 AM", "02:30 PM", "04:30 PM", "06:00 PM"],
  },
  {
    id: "doc-meera-iyer",
    name: "Dr. Meera Iyer",
    specialty: "Cardiologist",
    location: "Mumbai, Maharashtra",
    clinic: "Bandra Heart Clinic",
    exp: "18 Yrs",
    rating: 4.9,
    about: "Cardiologist in Bandra focused on preventive screening and long-term heart health plans.",
    availableSlots: ["09:00 AM", "11:00 AM", "01:30 PM", "04:00 PM", "06:00 PM"],
  },
  {
    id: "doc-arjun-nair",
    name: "Dr. Arjun Nair",
    specialty: "General Physician",
    location: "Bengaluru, Karnataka",
    clinic: "Indiranagar Family Clinic",
    exp: "7 Yrs",
    rating: 4.6,
    about: "Primary care physician in Indiranagar for everyday illnesses, follow-ups, and wellness visits.",
    availableSlots: ["09:30 AM", "11:00 AM", "12:30 PM", "03:30 PM", "05:00 PM"],
  },
  {
    id: "doc-sneha-kulkarni",
    name: "Dr. Sneha Kulkarni",
    specialty: "Dermatologist",
    location: "Pune, Maharashtra",
    clinic: "Koregaon Park Skin Clinic",
    exp: "12 Yrs",
    rating: 4.8,
    about: "Dermatologist in Koregaon Park treating acne, pigmentation, and hair fall concerns.",
    availableSlots: ["09:00 AM", "10:30 AM", "02:00 PM", "04:00 PM", "05:30 PM"],
  },
  {
    id: "doc-vikram-malhotra",
    name: "Dr. Vikram Malhotra",
    specialty: "Orthopedic",
    location: "New Delhi, Delhi",
    clinic: "Saket Bone & Joint Center",
    exp: "20 Yrs",
    rating: 4.9,
    about: "Orthopedic specialist in Saket helping patients recover from injury and manage joint pain.",
    availableSlots: ["09:00 AM", "10:30 AM", "01:00 PM", "03:30 PM", "05:30 PM"],
  },
];

const symptoms = [
  {
    id: "sym-fever",
    symptom: "Fever",
    keywords: ["fever", "temperature", "high temp"],
    medicine: "Paracetamol (Dolo 650)",
    advice: "Stay hydrated, rest well, and monitor your temperature. Seek a doctor if it stays high or lasts more than two days.",
    doctorType: "General Physician",
    severity: "Monitor closely",
  },
  {
    id: "sym-headache",
    symptom: "Headache",
    keywords: ["headache", "migraine", "head pain"],
    medicine: "Ibuprofen or Paracetamol",
    advice: "Rest in a quiet room, reduce screen time, and drink water. If pain is severe or frequent, consult a neurologist.",
    doctorType: "Neurologist",
    severity: "Usually manageable",
  },
  {
    id: "sym-cold",
    symptom: "Cold / Runny Nose",
    keywords: ["cold", "runny nose", "sneezing"],
    medicine: "Cetirizine or Vitamin C",
    advice: "Steam inhalation, warm fluids, and rest usually help. Watch for breathing difficulty or worsening symptoms.",
    doctorType: "General Physician",
    severity: "Usually manageable",
  },
  {
    id: "sym-acidity",
    symptom: "Acidity",
    keywords: ["acidity", "acid reflux", "heartburn"],
    medicine: "Antacid such as Digene",
    advice: "Avoid spicy food, eat smaller meals, and do not lie down right after eating.",
    doctorType: "Gastroenterologist",
    severity: "Monitor diet-related triggers",
  },
  {
    id: "sym-stomach-pain",
    symptom: "Stomach Pain",
    keywords: ["stomach pain", "abdominal pain", "cramps"],
    medicine: "Meftal-Spas or doctor-advised antispasmodic",
    advice: "Eat light meals, stay hydrated, and seek care quickly if the pain is severe or persistent.",
    doctorType: "Gastroenterologist",
    severity: "Needs attention if persistent",
  },
  {
    id: "sym-back-pain",
    symptom: "Back Pain",
    keywords: ["back pain", "lower back pain", "backache"],
    medicine: "Topical pain relief gel or doctor-advised NSAID",
    advice: "Avoid heavy lifting, improve posture, and use light stretching if it feels safe.",
    doctorType: "Orthopedic",
    severity: "Monitor mobility and pain level",
  },
  {
    id: "sym-toothache",
    symptom: "Toothache",
    keywords: ["toothache", "tooth pain", "gum pain"],
    medicine: "Pain relief only as advised until dental review",
    advice: "Avoid very hot or cold foods and arrange a dental visit soon, especially if there is swelling.",
    doctorType: "Dentist",
    severity: "Needs dental review",
  },
];

const defaultUser = {
  name: "Demo Patient",
  email: "demo@smartmed.app",
  password: "Demo@12345",
  phone: "+1 555 0100",
  age: 28,
  gender: "Male",
  bloodGroup: "O+",
  address: "123 Health Street, Wellness City, NY",
};

const starterReports = [
  {
    title: "Annual Wellness Summary",
    date: "2026-01-10",
    doctorName: "Dr. Kavita Shah",
    type: "Checkup",
    status: "Ready",
  },
  {
    title: "General Blood Count (CBC)",
    date: "2026-02-05",
    doctorName: "Dr. Mehul Desai",
    type: "Lab Report",
    status: "Ready",
  },
  {
    title: "Skin Allergy Screening",
    date: "2026-02-18",
    doctorName: "Dr. Priya Agarwal",
    type: "Lab Report",
    status: "Processing",
  },
];

const starterAppointments = [
  {
    doctorId: "doc-kavita-shah",
    date: "2026-01-10",
    time: "10:30 AM",
    status: "Completed",
  },
  {
    doctorId: "doc-mehul-desai",
    date: "2026-04-15",
    time: "04:00 PM",
    status: "Upcoming",
  },
];

module.exports = {
  doctors,
  symptoms,
  defaultUser,
  starterReports,
  starterAppointments,
};
